dist: trusty
sudo: required
language: generic
services:
  - docker

script:
  - bin/ci

notifications:
  slack:
    secure: u8HdclJiHWxBv0U0wiQQTtIi0FMNuH3d6lLvAqMGDFU3UZDNbazRlquE8CvKUz5WGfCbuuRnW+iFfQ63edsOxxC16InTgjPchy066LEXdVLja5ZoDHqI830sv94IfR9bA7HhYz+WtjFypp9Sobu7vVULObT9zHwS9TlbDlo8pUW9vGddma1plytmKf0kQm9KJzzzs4PgEcfBFYK2JcY/CdfDFofPPC72MEP2IoSCVy/D8K40lSiJhnectuc40eWU3mvIRNosG7HRZEZCi9M+MPqZtAlUUd6fCElpnEZhdw6RwXrZtcJB78cN1cCBVz7a8vv2Owuhth4zcvJmq87cT6d/0GfnN7vSHTM9dI+sLzNd0Gfkgt517qBGf4YkogO6zTOTviMkG6lu5w1omSmgB2eE+c5T6mikgW+FeuBrQlJsVp5UGqArqcGyw/tI4ovzRy3JEi82TrtRzTEfm/mDCtf0LL+2VGlupW+cuSPvAMPIY9Y+ffn8BctK4NlwZgBSzoPJ9gkZqyjYM06ZPTepdqhnAFN3QV8+qRAoBGNSdb6ZBRhBrxRkEp6TdJNVCCHsBb+BFburwlyEI5MWqjAm16IJKUBmkRRxY6MVYucPjsyMqWhXOuHiLtb6Z8+u3y20PmNQU7xyZK1b5ze7madsVMsbvkDqaecpYadlZHgPAWQ=
