dist: trusty
sudo: required
language: generic
services:
  - docker

script:
  - bin/ci

notifications:
  slack:
    secure: j/Mnn63pfugHrvK3fvV/1RXIRrDgGQYwhzXCvEvRp76QltEIvExuyL3BoHmVlR5xWA6TI9SAs29YoaB//dWCaSy37sgi28qX6v9VOv3YIaMTjgrGCReBIEgDQP8VvBw+6R78G1xAwSQSJ6KQPVW1dVKgHz9NwQGaplJYB8ylCz/UkRP+TY3kSgBJZGegp1oQZKAacOx6ui2V44uoQ7Cxtb9PfWh9CoQC7toI0V2blnvip2xb25h9Sa5RfAq2dODCnwUeA+okKzTmR+muUY1jjWrxie54UozOhwEDQr5R6cQufoYysa2aBbNAuE/AtWlnlBG7MHlpzuAmX/S1EMwi+1k0WE6UYXJAK0/pHbqnX2AE6NYQYoCv7pYDjIvf/MFaH8inn4TIYNDcVMTBTMPc65Cy/meN9ErCJUHle/eBAoiHl6SFvQwd32KFGP+YKnBs4hOop822UIa0MdoBUTXBhrZBzR4B/iFXmEuL4bjgWXK51qGu2/h0v/r2VjYV0snpmZS5YSu3prTacJlYeeTg4L4Nd/0PNqq5eur6cr7b9cxzkQBC6cxhQ/ezhnvkoidbSMMFUJb14PEjLJNsmYBawWMWZO/9OlENLKPxzOs5HtIUch/6aOru4yrhpAq5ZX5+IvtmmKmEnir1t4tNtKOM+wBxPADZqJg7mRK3rQCrmvM=
